### ISSUE TITLE
Password for admin

### ISSUE THREAD

**Issue by suriyhakrisna** [gowthamrajk/HealthCareManagement#1]

**Comment by gowthamrajk** [comment]
Use admin@gmail.com / admin123 as the credenrials for testing purpose.

You can also enhance the code when you are practicing, by including multiple admins, and add a admin table and custonize the logic accordingly, or even you can include roles table and validate each role (admin/user/doctor) if its a valid user everytime whenever they are trying to log in.

**Comment by suriyhakrisna** [comment]
Thank you for your response
